### ISSUE TITLE
No static files to be served up

### ISSUE THREAD

**Issue by strazzere** [carbonblack/cb-integration#25]
https://github.com/carbonblack/cb-integration/blob/0dfdb4ed42115ccc1d82be2bc7114db86e2a9855/cbint/flask_feed.py#L23

This currently is pointing at nothing which is causing an error to be thrown (since not static directory or files exist);
```
2018-09-26 19:56:47,551 DEBG 'yara' stderr output:
[2018-09-26 19:56:47,548] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/cbint-2.0.0-py3.6.egg/cbint/flask_feed.py", line 23, in basic_pages
    return make_response(open(os.path.join(os.path.dirname(os.path.realpath(__file__)), "static", "index.html")).read())
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/cbint-2.0.0-py3.6.egg/cbint/static/index.html'
```

**Comment by askthedragon** [comment]
Yea, we are still working on a UI.  I will remove that route until we are done
